export const ACTION_SHOW_OPTION_PAGE = 'SHOW_OPTION_PAGE';
export const ACTION_INTERCEPT_NETWORK_STAR_OPEN = 'INTERCEPT_NETWORK_STAR_OPEN';
export const ACTION_INTERCEPT_NETWORK_STAR_CLOSE = 'ACTION_INTERCEPT_NETWORK_STAR_CLOSE';

const ACTIONS = [
  ACTION_SHOW_OPTION_PAGE,
  ACTION_INTERCEPT_NETWORK_STAR_OPEN,
  ACTION_INTERCEPT_NETWORK_STAR_CLOSE,
] as const;

export interface IAction<T> {
  type: typeof ACTIONS[number];
  payload?: T;
}
