export const ACTION_SHOW_OPTION_PAGE = 'ACTION_SHOW_OPTION_PAGE';
export const ACTION_INTERCEPT_NETWORK_GET_INFO = 'ACTION_INTERCEPT_NETWORK_GET_INFO';
export const ACTION_INTERCEPT_NETWORK_STAR_ADD = 'ACTION_INTERCEPT_NETWORK_STAR_ADD';

const ACTIONS = [
  ACTION_SHOW_OPTION_PAGE,
  ACTION_INTERCEPT_NETWORK_GET_INFO,
  ACTION_INTERCEPT_NETWORK_STAR_ADD,
] as const;

export interface IAction<T> {
  type: typeof ACTIONS[number];
  payload?: T;
}
